## Выполнили студенты гр. 6405-010302D:
* Сорокин Д.М.
* Буторина П.В.
* Морозов А.Е.

# Лабораторная работа 2

## Часть 1

### Подключение библиотеки

In [2]:
import numpy as np

### 2.1 Сформировать порождающую матрицу линейного кода (7, 4, 3)

In [3]:
def generate_g_matrix():
    I_k = np.eye(4, dtype=int)
    X = np.array([
        [1, 1, 0],
        [1, 0, 1],
        [0, 1, 1],
        [1, 1, 1]
    ])
    G = np.hstack((I_k, X))
    return G

G = generate_g_matrix()
print("Пораждающая матрица G:\n", G)

Пораждающая матрица G:
 [[1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 1]]


### 2.2 Сформировать проверочную матрицу на основе порождающей

In [4]:
def generate_h_matrix(G):
    X = G[:, 4:]
    I_nk = np.eye(3, dtype=int)
    H = np.hstack((X.T, I_nk))
    return H

H = generate_h_matrix(G)
print("Проверочная матрица H:\n", H)

Проверочная матрица H:
 [[1 1 0 1 1 0 0]
 [1 0 1 1 0 1 0]
 [0 1 1 1 0 0 1]]


### 2.3 Сформировать таблицу синдромов для всех однократных ошибок

In [5]:
def generate_syndrome_table(H):
    n = H.shape[1]
    error_vectors = np.eye(n, dtype=int)
    syndrome_table = {tuple(H @ e % 2): e for e in error_vectors}
    return syndrome_table

syndrome_table = generate_syndrome_table(H)
print("Синдром:", "\t", "Вектор ошибки:")
for syndrome, error_vector in syndrome_table.items():
    print(syndrome, "\t", error_vector)

Синдром: 	 Вектор ошибки:
(1, 1, 0) 	 [1 0 0 0 0 0 0]
(1, 0, 1) 	 [0 1 0 0 0 0 0]
(0, 1, 1) 	 [0 0 1 0 0 0 0]
(1, 1, 1) 	 [0 0 0 1 0 0 0]
(1, 0, 0) 	 [0 0 0 0 1 0 0]
(0, 1, 0) 	 [0 0 0 0 0 1 0]
(0, 0, 1) 	 [0 0 0 0 0 0 1]


### 2.4 Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова

In [20]:
def encode_message(G, message):
    return message @ G % 2

def decode_message(H, received_word, syndrome_table):
    syndrome = tuple(H @ received_word % 2)
    if syndrome in syndrome_table:
        error = syndrome_table[syndrome]
        corrected_word = (received_word + error) % 2
        return corrected_word, error
    return received_word, None

def introduce_error(codeword, error_indices):
    error_vector = np.zeros(len(codeword), dtype=int)
    for i in error_indices:
        error_vector[i] = 1
    return (codeword + error_vector) % 2

message = np.array([1, 0, 1, 1])
print("Исходное слово:\n", message)
codeword = encode_message(G, message)
print("\nКодовое слово:\n", codeword)
received_word = introduce_error(codeword, [2])
print("\nПринятое слово с однократной ошибкой:\n", received_word)
corrected_word, error = decode_message(H, received_word, syndrome_table)
print("\nИспраавленное слово:\n", corrected_word)
print("\nОшибка:\n", error)

Исходное слово:
 [1 0 1 1]

Кодовое слово:
 [1 0 1 1 0 1 0]

Принятое слово с однократной ошибкой:
 [1 0 0 1 0 1 0]

Испраавленное слово:
 [1 0 1 1 0 1 0]

Ошибка:
 [0 0 1 0 0 0 0]


### 2.5 Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного

In [27]:
def attempt_double_error_correction(H, codeword, syndrome_table):
    received_word = introduce_error(codeword, [1, 4])
    syndrome = tuple(H @ received_word % 2)
    if syndrome in syndrome_table:
        error = syndrome_table[syndrome]
        corrected_word = (received_word + error) % 2
    else:
        corrected_word = received_word
        error = None
    return corrected_word, error

print("Исходное слово:\n", message)
print("\nКодовое слово:\n", codeword)
received_word_double_error, error_double = attempt_double_error_correction(H, codeword, syndrome_table)
print("\nПринятое слово с двукратной ошибкой:\n", received_word_double_error)
print("\nПопытка исправления двукратной ошибки:\n", received_word_double_error)
print("\nОшибка:\n", error_double)

Исходное слово:
 [0 1 1 0]

Кодовое слово:
 [0 1 1 0 1 1 0]

Принятое слово с двукратной ошибкой:
 [0 0 1 0 0 1 1]

Попытка исправления двукратной ошибки:
 [0 0 1 0 0 1 1]

Ошибка:
 [0 0 0 0 0 0 1]


## Часть 2

### 2.6 Сформировать порождающую матрицу линейного кода (n, k, 5)

In [22]:
def generate_g_matrix_5():
    I_k = np.eye(5, dtype=int)
    X = np.array([
        [1, 1, 1, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 1, 0]
    ])
    G = np.hstack((I_k, X))
    return G

G_5 = generate_g_matrix_5()
print("Пораждающая матрица G для кода (n, k, 5):\n", G_5)

Пораждающая матрица G для кода (n, k, 5):
 [[1 0 0 0 0 1 1 1 0 1]
 [0 1 0 0 0 0 1 1 1 1]
 [0 0 1 0 0 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0]]


### 2.7 Сформировать проверочную матрицу на основе порождающей

In [23]:
def generate_h_matrix_5(G):
    X = G[:, 5:]
    I_nk = np.eye(5, dtype=int)
    H = np.hstack((X.T, I_nk))
    return H

H_5 = generate_h_matrix_5(G_5)
print("Проверочная матрица H:\n", H_5)

Проверочная матрица H:
 [[1 0 1 1 1 1 0 0 0 0]
 [1 1 0 1 1 0 1 0 0 0]
 [1 1 1 0 1 0 0 1 0 0]
 [0 1 1 1 1 0 0 0 1 0]
 [1 1 1 1 0 0 0 0 0 1]]


### 2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок

In [24]:
def generate_syndrome_table_5(H):
    n = H.shape[1]
    error_vectors = np.eye(n, dtype=int)
    syndrome_table = {tuple(H @ e % 2): e for e in error_vectors}

    for i in range(n):
        for j in range(i + 1, n):
            error_vector = np.zeros(n, dtype=int)
            error_vector[i] = 1
            error_vector[j] = 1
            syndrome_table[tuple(H @ error_vector % 2)] = error_vector
    return syndrome_table

syndrome_table_5 = generate_syndrome_table_5(H_5)
print("Синдром:", "\t\t", "Вектор ошибки:")
for syndrome_5, error_vector_5 in syndrome_table_5.items():
    print(syndrome_5, "\t", error_vector_5)

Синдром: 		 Вектор ошибки:
(1, 1, 1, 0, 1) 	 [1 0 0 0 0 0 0 0 0 0]
(0, 1, 1, 1, 1) 	 [0 1 0 0 0 0 0 0 0 0]
(1, 0, 1, 1, 1) 	 [0 0 1 0 0 0 0 0 0 0]
(1, 1, 0, 1, 1) 	 [0 0 0 1 0 0 0 0 0 0]
(1, 1, 1, 1, 0) 	 [0 0 0 0 1 0 0 0 0 0]
(1, 0, 0, 0, 0) 	 [0 0 0 0 0 1 0 0 0 0]
(0, 1, 0, 0, 0) 	 [0 0 0 0 0 0 1 0 0 0]
(0, 0, 1, 0, 0) 	 [0 0 0 0 0 0 0 1 0 0]
(0, 0, 0, 1, 0) 	 [0 0 0 0 0 0 0 0 1 0]
(0, 0, 0, 0, 1) 	 [0 0 0 0 0 0 0 0 0 1]
(1, 0, 0, 1, 0) 	 [0 0 0 0 0 1 0 0 1 0]
(0, 1, 0, 1, 0) 	 [0 0 0 0 0 0 1 0 1 0]
(0, 0, 1, 1, 0) 	 [0 0 0 0 0 0 0 1 1 0]
(0, 0, 0, 1, 1) 	 [0 0 0 0 0 0 0 0 1 1]
(0, 1, 1, 0, 1) 	 [0 1 0 0 0 0 0 0 1 0]
(1, 0, 1, 0, 1) 	 [0 0 1 0 0 0 0 0 1 0]
(1, 1, 0, 0, 1) 	 [0 0 0 1 0 0 0 0 1 0]
(1, 1, 1, 1, 1) 	 [0 0 0 0 1 0 0 0 0 1]
(1, 1, 1, 0, 0) 	 [0 0 0 0 1 0 0 0 1 0]
(1, 1, 0, 0, 0) 	 [0 0 0 0 0 1 1 0 0 0]
(1, 0, 1, 0, 0) 	 [0 0 0 0 0 1 0 1 0 0]
(1, 0, 0, 0, 1) 	 [0 0 0 0 0 1 0 0 0 1]
(0, 0, 1, 1, 1) 	 [0 0 1 0 0 1 0 0 0 0]
(0, 1, 0, 1, 1) 	 [0 0 0 1 0 1 0 0 0 0]
(0, 1, 1, 1, 

### 2.9 Сформировать кодовое слово длины n из слова длины k. Внести однократную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова

In [28]:
def encode_message_5(G, message):
    return message @ G % 2


def decode_message_5(H, received_word, syndrome_table):
    syndrome = tuple(H @ received_word % 2)
    if syndrome in syndrome_table:
        error = syndrome_table[syndrome]
        corrected_word = (received_word + error) % 2
        return corrected_word, error
    return received_word, None


def introduce_error_5(codeword, error_indices):
    error_vector = np.zeros(len(codeword), dtype=int)
    for i in error_indices:
        error_vector[i] = 1
    return (codeword + error_vector) % 2

message_5 = np.array([1, 0, 1, 1, 0])
print("Исходное слово:\n", message_5)
codeword_5 = encode_message_5(G_5, message_5)
print("\nКодовое слово:\n", codeword_5)
received_word_5 = introduce_error_5(codeword_5, [2])
print("\nПринятое слово с однократной ошибкой:\n", received_word_5)
corrected_word_5, error_5 = decode_message_5(H_5, received_word_5, syndrome_table_5)
print("\nИсправленное слово:\n", corrected_word_5)
print("\nОшибка:\n", error_5)

Исходное слово:
 [1 0 1 1 0]

Кодовое слово:
 [1 0 1 1 0 1 0 0 0 1]

Принятое слово с однократной ошибкой:
 [1 0 0 1 0 1 0 0 0 1]

Исправленное слово:
 [1 0 1 1 0 1 0 0 0 1]

Ошибка:
 [0 0 1 0 0 0 0 0 0 0]


### 2.10. Сформировать кодовое слово длины n из слова длины k. Внести двукратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться в правильности полученного слова

In [29]:
print("Исходное слово:\n", message_5)
print("\nКодовое слово:\n", codeword_5)

received_word_5 = introduce_error_5(codeword_5, [1, 4])
print("\nПринятое слово с двукратной ошибкой:\n", received_word_5)
corrected_word_5, error_5 = decode_message_5(H_5, received_word_5, syndrome_table_5)
print("\nИсправленное слово:\n", corrected_word_5)
print("\nОшибка:\n", error_5)

Исходное слово:
 [1 0 1 1 0]

Кодовое слово:
 [1 0 1 1 0 1 0 0 0 1]

Принятое слово с двукратной ошибкой:
 [1 1 1 1 1 1 0 0 0 1]

Исправленное слово:
 [1 1 1 1 1 0 0 0 0 0]

Ошибка:
 [0 0 0 0 0 1 0 0 0 1]


### 2.11. Сформировать кодовое слово длины n из слова длины k. Внести трёхкратную ошибку в сформированное слово. Вычислить синдром, исправить ошибку с использованием таблицы синдромов. Убедиться, что полученное слово отличается от отправленного

In [30]:
print("Исходное слово:\n", message_5)
print("\nКодовое слово:\n", codeword_5)

received_word_5 = introduce_error_5(codeword_5, [0, 2, 4])
print("\nПринятое слово с трёхкратной ошибкой:\n", received_word_5)
corrected_word_5, error_5 = decode_message_5(H_5, received_word_5, syndrome_table_5)
print("\nИсправленное слово:\n", corrected_word_5)
print("\nОшибка:\n", error_5)

Исходное слово:
 [1 0 1 1 0]

Кодовое слово:
 [1 0 1 1 0 1 0 0 0 1]

Принятое слово с трёхкратной ошибкой:
 [0 0 0 1 1 1 0 0 0 1]

Исправленное слово:
 [0 0 0 1 1 0 0 1 0 1]

Ошибка:
 [0 0 0 0 0 1 0 1 0 0]
