# Лабораторная работа 4

## Часть 1

### 4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8).


In [125]:
import numpy as np
import random
from itertools import product
import random

In [126]:
# config
n, k, d = 24, 12, 8

In [127]:
def golay_matrix():
    B = np.array([[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
              [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
              [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
              [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
              [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
              [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
              [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
              [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
              [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]], dtype=int)
    
    G = np.hstack((np.eye(len(B), dtype=int), B))
    H = np.vstack((np.eye(len(B), dtype=int), B))
    
    return B, G, H

In [128]:
B, G, H = golay_matrix()
print("Порождающая матрица G:")
print(G)
print("\nПроверочная матрица H:")
print(H)

Порождающая матрица G:
[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]

Проверочная матрица H:
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 

### 4.2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.

In [129]:
def gen_error_words(word, n_errors):
    tmp_word = word.copy()
    error_indices = random.sample(range(len(tmp_word)), n_errors)
    
    for index in error_indices:
        tmp_word[index] ^= 1
    
    return tmp_word


def decode_words(word, H):
    return np.dot(word, H) % 2


def calc_error_vector(s, B):
    u = np.array([])
    if sum(s) <= 3:
        u = np.hstack((s, np.zeros(len(B), dtype=int)))
        return u
    
    # e_i - вектор с единственной единицей по индексу i
    for j in range(len(B)):
        if sum(s + B[j]) <= 2:
            e_i = np.zeros(12, dtype=int)
            e_i[j] = 1
            u = np.hstack(((s + B[j]) % 2, e_i))
            return u
    
    if u.size == 0:
        sB = (s @ B) % 2
        if sum(sB) <= 3:
            u = np.hstack((np.zeros(12, dtype=int), sB))
            return u
    
        for j in range(len(B)):
            if sum((sB + B[j]) % 2) <= 2:
                e_i = np.zeros(12, dtype=int)
                e_i[j] = 1
                u = np.hstack((e_i, (sB + B[j]) % 2))
                return u
    return np.array([])
        

def analise_golay(B, G, H):
    k = 12
    message = np.random.randint(2, size=k)
    code = np.dot(message, G) % 2
    
    print("Сообщение: ", message)
    print("Закодированное слово: ", code)
    print()
    
    words = [[0, 1] for _ in range(k)]
    words = np.array(list(product(*words)))

    # создаем словарь: ключ - кодовое слово, значение исходное сообщение
    w_dict = {np.array_str((el @ G)% 2): el for el in words}
    
    for i in range(1, 5):
        print("Кол-во ошибок: ", i)
        error_code = gen_error_words(code, i)
        print("Кодовое слово с ошибками: ", error_code)
        # вычисляем синдром
        s = np.array(decode_words(error_code, H))
        print("Синдром: ", s)

        u = calc_error_vector(s, B)

        if u.size != 0:
            print(f"Исходное слово: {w_dict[np.array_str((error_code + u) % 2)]}\n")
        else:
            print("Невозможно вычислить, так как кратность ошибки выше 3")
            
analise_golay(B, G, H)

Сообщение:  [1 0 1 1 1 0 0 0 1 0 0 0]
Закодированное слово:  [1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 1]

Кол-во ошибок:  1
Кодовое слово с ошибками:  [1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1]
Синдром:  [0 1 1 0 1 1 1 0 0 0 1 1]
Исходное слово: [1 0 1 1 1 0 0 0 1 0 0 0]

Кол-во ошибок:  2
Кодовое слово с ошибками:  [1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 1 0 1]
Синдром:  [1 0 1 0 1 0 0 0 1 0 1 1]
Исходное слово: [1 0 1 1 1 0 0 0 1 0 0 0]

Кол-во ошибок:  3
Кодовое слово с ошибками:  [1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1]
Синдром:  [1 1 0 0 0 1 1 1 0 1 1 0]
Исходное слово: [1 0 1 1 1 0 0 0 1 0 0 0]

Кол-во ошибок:  4
Кодовое слово с ошибками:  [1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0]
Синдром:  [0 1 0 1 0 1 0 0 1 0 0 0]
Невозможно вычислить, так как кратность ошибки выше 3


## Часть 2

### 4.3 Написать функцию формирования порождающей и проверочных матриц кода Рида-Маллера 𝑅𝑀(𝑟, 𝑚) на основе параметров 𝑟 и 𝑚.

In [130]:
def RM(r, m):
    if r == 0:
        return np.ones((1, 2 ** m), dtype=int)
    if r == m:
        return np.vstack((RM(m - 1, m), np.array([0 for _ in range(2 ** m - 1)] + [1])))
    mat = RM(r, m - 1)
    mat2 = RM(r - 1, m - 1)
    return np.vstack((np.hstack((mat, mat)), np.hstack((np.zeros((mat2.shape[0], mat.shape[1]), dtype=int), mat2))))


def kron(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    result = np.zeros((rows_A * rows_B, cols_A * cols_B), dtype=A.dtype)
    for i in range(rows_A):
        for j in range(cols_A):
            result[i * rows_B:(i + 1) * rows_B, j * cols_B:(j + 1) * cols_B] = A[i, j] * B
    return result


def H_matrix(H, m, i):
    matrix = np.eye(2 ** (m - i), dtype=int)
    matrix = kron(matrix, H)
    matrix = kron(matrix, np.eye(2 ** (i - 1)))
    return matrix


def calc_error_rm(word, m):
    word = np.where(word == 0, -1, word)  # Заменяем 0 на -1
    w_array = []
    H = np.array([[1, 1], [1, -1]])
    w_array.append(word @ H_matrix(H, m, 1))
    for i in range(2, m + 1):
        w_array.append(w_array[-1] @ H_matrix(H, m, i))
    w_last = w_array[-1]  # Используем только последний уровень

    max_value = np.max(np.abs(w_last))
    indices = np.where(np.abs(w_last) == max_value)[0]

    if len(indices) > 1:
        return None  # Несколько максимумов, невозможно исправить ошибку

    index = indices[0]
    message = list(map(int, format(index, f'0{m}b')))  # Индекс в двоичное представление
    message.append(1 if w_last[index] > 0 else 0)  # Добавляем бит определения
    return message


def analise_golay(r, m, u, e):
    print("Сообщение:", u)
    print(f"Порождающая матрица для RM({r}, {m}):")
    G = RM(r, m)
    print(G)
    print()
    word = u @ G % 2
    print("Закодированное слово:", word)

    for i in range(1, e + 1):
        error = np.zeros(word.shape[0], dtype=int)
        error_indices = random.sample(range(word.shape[0]), i)
        for index in error_indices:
            error[index] = 1

        print("\nКоличество ошибок:", i)
        print("Допущенная ошибка:", error)
        word_with_error = (word + error) % 2
        print("Сообщение с ошибкой:", word_with_error)

        message = calc_error_rm(word_with_error, m)
        if message is None:
            print("Невозможно исправить ошибку!")
        else:
            corrected_message = np.array(message[::-1])
            print("Исправленное сообщение:", corrected_message)
            if np.array_equal(u, corrected_message):
                print("Сообщение успешно декодировано!")
            else:
                print("Сообщение было декодировано с ошибкой!")

### 4.4. Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и двукратных ошибок.


In [131]:
u = np.array([1, 0, 0, 1])
analise_golay(1, 3, u, 2)

Сообщение: [1 0 0 1]
Порождающая матрица для RM(1, 3):
[[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]

Закодированное слово: [1 1 1 1 0 0 0 0]

Количество ошибок: 1
Допущенная ошибка: [0 0 0 0 1 0 0 0]
Сообщение с ошибкой: [1 1 1 1 1 0 0 0]
Исправленное сообщение: [1 0 0 1]
Сообщение успешно декодировано!

Количество ошибок: 2
Допущенная ошибка: [0 0 1 0 0 0 1 0]
Сообщение с ошибкой: [1 1 0 1 0 0 1 0]
Невозможно исправить ошибку!


### 4.5. Провести исследование кода Рида-Маллера 𝑅𝑀(1,4) для одно-, двух-, трёх- и четырёхкратных ошибок.

In [132]:
u = np.array([1, 0, 1, 0, 1])
analise_golay(1, 4, u, 4)


Сообщение: [1 0 1 0 1]
Порождающая матрица для RM(1, 4):
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]

Закодированное слово: [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]

Количество ошибок: 1
Допущенная ошибка: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой: [0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]
Сообщение успешно декодировано!

Количество ошибок: 2
Допущенная ошибка: [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
Сообщение с ошибкой: [0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]
Сообщение успешно декодировано!

Количество ошибок: 3
Допущенная ошибка: [0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
Сообщение с ошибкой: [1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 1]
Исправленное сообщение: [1 0 1 0 1]
Сообщение успешно декодировано!

Количество ошибок: 4
Допущенная ошибка: [0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0]
Сообщение с ошибкой: [1 1 0 1 1 1 0 0 1 0